"""Email-safe copy of the Wispr Flow daily brief for Aqua Voice.
Reads brief.json (generated by brief_to_json.mjs from the same file the web report
renders) so the email and the report cannot drift. All CSS inlined, tables only.
Writes <DATE>.email.html and <DATE>.email.txt."""
import html, json, re, pathlib

DATE = "09-01-2026"
HERE = pathlib.Path(__file__).parent
BRIEF = json.loads((HERE / "brief.json").read_text(encoding="utf-8"))
SRC = BRIEF["sources"]

LINK = "color:#3366cc;text-decoration:none"
FONT = "font-family:Arial,Helvetica,sans-serif"
CELL = "border:1px solid #c8ccd1;font:13px Arial,sans-serif;color:#202122"
HEAD = CELL + ";background:#f8f9fa;font-weight:bold"
BODY = f"{FONT};font-size:14px;line-height:1.55;color:#202122;margin:0 0 12px"
NOTE = f"{FONT};font-size:13px;line-height:1.5;color:#72777d;margin:0 0 12px"
PILL = f"color:#54595d;text-decoration:none;font-size:12px"
TONE = {"good": "#1baf7a", "bad": "#d33", "neutral": "#72777d"}


def md(s):
    """The brief's inline markup: **bold**, [label](href), [[source]], [[source|Label]]."""
    s = html.escape(s, quote=False)
    s = re.sub(r"\[\[([a-z0-9\-]+)\|([^\]]+)\]\]",
               lambda m: pill(m.group(1), m.group(2)), s)
    s = re.sub(r"\[\[([a-z0-9\-]+)\]\]", lambda m: pill(m.group(1)), s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)",
               lambda m: f'<a href="{m.group(2)}" style="{LINK}">{m.group(1)}</a>', s)
    s = re.sub(r"\*\*(.+?)\*\*", r'<b style="font-weight:bold">\1</b>', s)
    return s


def pill(sid, label=None):
    d = SRC.get(sid)
    if not d:
        return ""
    text = html.escape(label or d["label"], quote=False)
    return (f'<a href="{html.escape(d["href"])}" style="{PILL}">'
            f'<span style="background:#f8f9fa;border:1px solid #c8ccd1;padding:1px 5px;'
            f'border-radius:3px;white-space:nowrap">{text}</span></a>')


def h1(t):
    return f'<p style="{FONT};font-size:26px;line-height:1.2;font-weight:bold;color:#202122;margin:0 0 4px">{t}</p>'


def sub(t):
    return (f'<p style="{FONT};font-size:13px;color:#72777d;margin:0 0 18px;padding-bottom:10px;'
            f'border-bottom:1px solid #c8ccd1">{t}</p>')


def h2(t):
    n, _, rest = t.partition(". ")
    return (f'<p style="{FONT};font-size:18px;line-height:1.3;font-weight:bold;color:#202122;'
            f'margin:30px 0 8px;padding-bottom:5px;border-bottom:1px solid #c8ccd1">'
            f'<span style="color:#72777d;font-weight:normal">{n}</span> {rest}</p>')


def h3(t):
    return (f'<p style="{FONT};font-size:15px;font-weight:bold;color:#202122;margin:20px 0 6px">'
            f'{md(t)}</p>')


def rulebox(inner, colour="#1baf7a", text="#202122"):
    return ('<table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:6px 0 14px"><tr>'
            f'<td width="3" bgcolor="{colour}" style="background-color:{colour};font-size:1px;line-height:1px">&nbsp;</td>'
            f'<td style="padding:2px 0 2px 12px;{FONT};font-size:14px;line-height:1.55;color:{text}">'
            f'{inner}</td></tr></table>')


def bullet(inner, colour="#72777d"):
    return ('<table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>'
            f'<td width="18" valign="top" style="{FONT};font-size:15px;line-height:1.5;color:{colour}">&bull;</td>'
            f'<td style="{FONT};font-size:14px;line-height:1.55;color:#202122;padding-bottom:9px">'
            f'{inner}</td></tr></table>')


def details(summary_html, inner_html, summary_style=None, wrap_margin="0 0 14px"):
    """Collapsible block. Apple Mail honours <details>. Gmail and Outlook strip the tag
    and render the body expanded, which is the same email we sent before, so nothing is
    ever hidden from anyone. No CSS marker override: clients that drop <details> then
    show the summary as a plain bold heading."""
    ss = summary_style or (f"{FONT};font-size:15px;font-weight:bold;color:#202122;"
                           f"cursor:pointer;margin:18px 0 6px")
    return (f'<details style="margin:{wrap_margin}">'
            f'<summary style="{ss}">{summary_html}</summary>'
            f'<table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>'
            f'<td style="padding:8px 0 0 2px">{inner_html}</td></tr></table></details>')


def table(headers, rows):
    widths = [h.get("w", "") for h in headers]
    out = ['<table width="100%" cellpadding="7" cellspacing="0" border="0" '
           'style="border-collapse:collapse;border:1px solid #a2a9b1;line-height:1.45;margin:6px 0 16px"><tr>']
    for h_, w in zip(headers, widths):
        wa = f' width="{w}"' if w else ""
        out.append(f'<td{wa} valign="top" bgcolor="#f8f9fa" style="{HEAD}">{md(h_["text"])}</td>')
    out.append("</tr>")
    for r in rows:
        out.append("<tr>")
        for h_, c in zip(headers, r):
            nw = ";white-space:nowrap" if h_.get("nw") else ""
            out.append(f'<td valign="top" style="{CELL}{nw}">{md(c)}</td>')
        out.append("</tr>")
    out.append("</table>")
    return "".join(out)


def blocks(bs, depth=0):
    out = []
    for b in bs:
        t = b["type"]
        if t == "p":
            out.append(f'<p style="{BODY}">{md(b["text"])}</p>')
        elif t == "note":
            out.append(f'<p style="{NOTE}">{md(b["text"])}</p>')
        elif t == "why":
            out.append(rulebox(md(b["text"])))
        elif t == "h3":
            out.append(h3(b["text"]))
        elif t == "table":
            out.append(table(b["headers"], b["rows"]))
        elif t == "links":
            for item in b["items"]:
                out.append(f'<p style="{NOTE};margin:0 0 7px;line-height:2">{md(item)}</p>')
        elif t == "ul":
            for it in b["items"]:
                out.append(bullet(md(it)))
        elif t == "changes":
            for it in b["items"]:
                out.append(bullet(md(it["text"]), TONE.get(it.get("tone", "neutral"), "#72777d")))
        elif t == "moves":
            for i, m in enumerate(b["items"], 1):
                head = f'<b style="font-weight:bold">{i}. {md(m["action"])}</b>'
                why = f'<span style="color:#404244">{md(m["why"])}</span>'
                if b.get("collapsed"):
                    ss = (f"{FONT};font-size:14px;line-height:1.55;color:#202122;"
                          f"cursor:pointer;margin:0")
                    inner = details(head, why, summary_style=ss, wrap_margin="0")
                else:
                    inner = f"{head}<br>{why}"
                out.append(rulebox(inner))
        elif t == "findings":
            for f_ in b["items"]:
                out.append(details(md(f_["claim"]), "".join(blocks(f_["body"], depth + 1))))
        elif t == "toggle":
            out.append(details(md(b["claim"]), "".join(blocks(b["body"], depth + 1))))
    return out


b = [h1(BRIEF["title"]), sub(BRIEF["sub"])]
b.append('<table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;'
         'border:1px solid #a2a9b1;margin:2px 0 16px"><tr><td bgcolor="#f8f9fa" '
         f'style="background:#f8f9fa;padding:8px 18px 8px 14px;{FONT};font-size:14px;line-height:1.5;color:#202122">'
         '<span style="font-weight:bold">Contents</span><br>'
         + "<br>".join(html.escape(s["title"], quote=False) for s in BRIEF["sections"])
         + '</td></tr></table>')
INTRO = [dict(x) for x in BRIEF["intro"]]
for x in INTRO:
    if x["type"] == "note" and "collapsed" in x["text"]:
        x["text"] = ("Each finding below is collapsed. Open one to see the evidence and the "
                     "sources. If your mail app shows them already open, that is fine, nothing "
                     "is hidden.")
b += blocks(INTRO)
for s in BRIEF["sections"]:
    b.append(h2(s["title"]))
    b += blocks(s["blocks"])

b.append(f'<p style="{NOTE};margin-top:26px;padding-top:12px;border-top:1px solid #c8ccd1">'
         + md(BRIEF["footer"]) +
         f' <a href="{{{{{{RESEND_UNSUBSCRIBE_URL}}}}}}" style="{LINK}">Unsubscribe</a>.</p>')

PREVIEW = ("7 people said Wispr got worse on Aug 31. superwhisper started advertising in Japan. "
           "5 ads and 5 creators worth copying.")

html_out = ('<!DOCTYPE html><html><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width, initial-scale=1.0">'
            '<meta http-equiv="X-UA-Compatible" content="IE=edge">'
            f'<title>{BRIEF["title"]}, Sep 1</title></head>'
            '<body style="margin:0;background-color:#ffffff">'
            f'<div style="display:none;max-height:0;overflow:hidden;opacity:0">{PREVIEW}</div>'
            '<div style="background-color:#ffffff;padding:24px 0">'
            '<table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>'
            '<td align="center"><table width="900" cellpadding="0" cellspacing="0" border="0" '
            'style="max-width:900px;width:100%"><tr><td style="padding:0 20px">'
            + "".join(b) +
            '</td></tr></table></td></tr></table></div></body></html>')
(HERE / f"{DATE}.email.html").write_text(html_out, encoding="utf-8")


# ---------- plain text ----------
def strip(s):
    s = re.sub(r"\[\[([a-z0-9\-]+)\|([^\]]+)\]\]", r"\2", s)
    s = re.sub(r"\[\[([a-z0-9\-]+)\]\]", lambda m: SRC.get(m.group(1), {}).get("label", ""), s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r"\1 (\2)", s)
    s = s.replace("**", "")
    return re.sub(r"\s+", " ", s).strip()


def txt_blocks(bs, t):
    for b_ in bs:
        ty = b_["type"]
        if ty in ("p", "note"):
            t += [strip(b_["text"]), ""]
        elif ty == "why":
            t += [strip(b_["text"]), ""]
        elif ty == "h3":
            t += [strip(b_["text"]).upper(), ""]
        elif ty == "moves":
            for i, m in enumerate(b_["items"], 1):
                t += [f'{i}. {strip(m["action"])}', f'   {strip(m["why"])}', ""]
        elif ty == "findings":
            for f_ in b_["items"]:
                t += [f'* {strip(f_["claim"])}']
                txt_blocks(f_["body"], t)
        elif ty == "changes":
            for it in b_["items"]:
                t += [f'* {strip(it["text"])}', ""]
        elif ty == "links":
            for it in b_["items"]:
                t += [strip(it)]
            t.append("")
        elif ty == "table":
            hs = [h_["text"] for h_ in b_["headers"]]
            for r in b_["rows"]:
                t.append("* " + " | ".join(f"{k}: {strip(v)}" for k, v in zip(hs, r)))
                t.append("")
    return t


t = [BRIEF["title"].upper(), BRIEF["sub"], ""]
txt_blocks(BRIEF["intro"], t)
for s in BRIEF["sections"]:
    t += [s["title"].upper(), "-" * len(s["title"])]
    txt_blocks(s["blocks"], t)
t += ["---", strip(BRIEF["footer"]), "Unsubscribe: {{{RESEND_UNSUBSCRIBE_URL}}}"]
(HERE / f"{DATE}.email.txt").write_text("\n".join(t), encoding="utf-8")

print(f"{DATE}.email.html {len(html_out)} bytes ({len(html_out)/1024:.1f} KB)")
print(f"{DATE}.email.txt  {len(chr(10).join(t))} bytes")
